name: Docker MySQL Proxy

on: [push]

env:
  DOCKER_TAG: latest
  DOCKER_IMAGE_DHUB: matthewbaggett/mysql-proxy
  DOCKER_IMAGE_GITHUB: docker.pkg.github.com/matthewbaggett/docker-mysql-proxy/docker-mysql-proxy

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to registries
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker login docker.pkg.github.com -u ${{ secrets.GITHUB_USERNAME }} -p ${{ secrets.GITHUB_PASSWORD }}
    - name: Build the image
      run: docker build . --file Dockerfile --tag mysql-proxy
    - name: Tag image
      run: |
        docker tag mysql-proxy $DOCKER_IMAGE_DHUB:$DOCKER_TAG
        docker tag mysql-proxy $DOCKER_IMAGE_GITHUB:$DOCKER_TAG
    - name: Publish image to Registries
      run: |
        docker push $DOCKER_IMAGE_DHUB:$DOCKER_TAG
        docker push $DOCKER_IMAGE_GITHUB:$DOCKER_TAG

